services:
  postgres-order:
    container_name: postgres-order
    image: postgres
    environment:
      POSTGRES_DB: order-service
      POSTGRES_USER: ptechie
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-order:/data/postgres
    ports:
      - "5431:5432"
    restart: unless-stopped
    networks:
      - invms_network

  postgres-inventory:
    container_name: postgres-inventory
    image: postgres
    environment:
      POSTGRES_DB: inventory-service
      POSTGRES_USER: ptechie
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-inventory:/data/postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - invms_network

  postgres-developer:
    container_name: postgres-developer
    image: postgres
    environment:
      POSTGRES_DB: developer-service
      POSTGRES_USER: ptechie
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./postgres-developer:/data/postgres
    ports:
      - "5433:5432"
    restart: always
    networks:
      - invms_network

  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:5.7
    volumes:
      - ./mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    restart: always
    networks:
      - invms_network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:18.0.0
    pull_policy: always
    command: start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: auth.invms.xyz
    volumes:
      - ./keycloak_data:/opt/keycloak/data
    depends_on:
      - keycloak-mysql
    restart: always
    networks:
      - invms_network

  discovery-server:
    image: majdissa34/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password
    restart: always
    networks:
      - invms_network

  api-gateway:
    image: majdissa34/api-gateway:latest
    container_name: api-gateway
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password
    depends_on:
      - discovery-server
      - keycloak
    restart: always
    networks:
      - invms_network

  product-service:
    container_name: product-service
    image: majdissa34/product-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MONGO_URI=mongodb+srv://majd34:GJK*Bqh4Uff9tE-@product.3lvt3ij.mongodb.net/?retryWrites=true&w=majority&appName=Product
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password
      - JAVA_TOOL_OPTIONS=-Djdk.tls.client.protocols=TLSv1.2
    depends_on:
      - discovery-server
    restart: always
    networks:
      - invms_network

  order-service:
    container_name: order-service
    image: majdissa34/order-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres-order:5432/order-service
      - DB_USER=ptechie
      - DB_PASS=password
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password
      - INVENTORY_SERVICE_URL=http://inventory-service
    depends_on:
      - postgres-order
      - discovery-server
    restart: always
    networks:
      - invms_network

  inventory-service:
    container_name: inventory-service
    image: majdissa34/inventory-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres-inventory:5432/inventory-service
      - DB_USER=ptechie
      - DB_PASS=password
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password
    depends_on:
      - postgres-inventory
      - discovery-server
    restart: always
    networks:
      - invms_network

  developer-service:
    container_name: developer-service
    image: majdissa34/developer-service:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres-developer:5432/developer-service
      - DB_USER=ptechie
      - DB_PASS=password
      - EUREKA_USERNAME=eureka
      - EUREKA_PASSWORD=password
    depends_on:
      - postgres-developer
      - discovery-server
    restart: always
    networks:
      - invms_network

  nginx:
    image: nginx:latest
    container_name: nginx
    pull_policy: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - api-gateway
      - keycloak
      - discovery-server
    restart: always
    networks:
      - invms_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    pull_policy: always
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - invms_network

networks:
  invms_network:
    driver: bridge